project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Lingfeng Pan"
  site-url: https://lingfeng2324.github.io
  favicon: images/eibsee2.jpg
  repo-url: https://github.com/Lingfeng2324/Lingfeng2324.github.io
  repo-actions: [issue]

  page-footer:
    left: |
      Lingfeng Pan<br>
      [lingfengpan@outlook.com](mailto:lingfengpan@outlook.com)
    right: |
      [Google Scholar](https://scholar.google.com/citations?hl=en&user=1Wkzyd8AAAAJ&view_op=list_works&sortby=pubdate)<br>
      [ORCID](https://orcid.org/0009-0004-5846-3216)

  navbar:
    background: "#A9CCE3"
    search: true
    right:
      - text: "Home"
        href: index.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "中文"
        href: Chinese.qmd

format:
  html:
    theme: styles.scss
    toc: true
    toc-position: right
    toc-depth: 3
